modLoader="javafml"
loaderVersion="[36,)"
license="Academic Free License v3.0"

[[mods]]
modId="the_wet_smp_rehydrated"
version="Judgement Day"
displayName="The Wet SMP Rehydrated"
credits="IT WAS ME"
displayURL="https://www.youtube.com/"
authors="oreli bitch"
description='''
FUCK
'''

[[dependencies.the_wet_smp_rehydrated]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




