modLoader="javafml"
loaderVersion="[37,)"
license="Custom license"

[[mods]]
modId="the_wet_smp_rehydrated"
version="1.0.0"
displayName="The Wet SMP Rehydrated"
credits="the fun gang"
displayURL="https://www.google.com"
logoFile="logo.png"
authors="the fun gang"
description='''
its the moist multiplayer incident
'''

[[dependencies.the_wet_smp_rehydrated]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1]"
    ordering="NONE"
    side="BOTH"




