modLoader="javafml"
loaderVersion="[36,)"
license="Custom license"

[[mods]]
modId="the_wet_smp_rehydrated"
version="development version"
displayName="The Wet SMP Rehydrated"
credits="the fun gang & andy"
displayURL="https://www.youtube.com/"
logoFile="logo.png"
authors="the fun gang"
description='''
andy i compiled this for you please don't leak it
'''

[[dependencies.the_wet_smp_rehydrated]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




